# Generated by Django 2.2.3 on 2020-02-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agent_client_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userImage',
            field=models.ImageField(null=True, upload_to='static/profiles'),
        ),
        migrations.AddField(
            model_name='pro',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='businessName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='free_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='id_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='id_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='locationOfService',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='scannedId',
            field=models.FileField(null=True, upload_to='static/IDS'),
        ),
    ]
