# Generated by Django 2.2.3 on 2020-02-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='specialties',
            field=models.ManyToManyField(to='accounts.Specialty'),
        ),
    ]
