# Generated by Django 2.2.3 on 2020-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'Specialties'},
        ),
        migrations.AddField(
            model_name='pro',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
