# Generated by Django 2.2.3 on 2020-03-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='points',
        ),
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
