# Generated by Django 2.2.3 on 2020-03-25 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200308_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField(default=0.0)),
                ('momo_number', models.CharField(max_length=14, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sos Account',
            },
        ),
    ]
