# Generated by Django 2.2.3 on 2020-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='mode',
            field=models.CharField(choices=[('created', 'created'), ('quoted', 'quoted'), ('transit', 'transit'), ('completed', 'completed')], default='created', max_length=20, null=True),
        ),
    ]
