# Generated by Django 2.2.3 on 2020-03-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_auto_20200301_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='points',
            field=models.FloatField(default=10.0, help_text='This is how much points that are required to submit a quote for this request'),
        ),
    ]
